### ISSUE TITLE
bulk create product variations

### ISSUE THREAD

**Issue by ahmedabdelaalolltek** [SallaApp/express-starter-kit#152]
I want to create multi product varitions and when I call create varition api in for loop I got 423 error http status code, do you have bulk api to avoid multi api call 
thanks

**Comment by jamalla2** [comment]
> I want to create multi product varitions and when I call create varition api in for loop I got 423 error http status code, do you have bulk api to avoid multi api call thanks

Currently, the bulk update feature is only available for updating prices of products, which is done by passing an array of products with their updated prices. Unfortunately, the same functionality is not yet available for product options and variations. You will need to make individual API calls for creating variations until a bulk API for this specific functionality is implemented.
